## -*- encoding: utf-8 -*-
## This file (crap.sagetex.sage) was *autogenerated* from crap.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('crap', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = 7
_st_.blockbegin()
try:
 x=var(`x`)
except:
 _st_.goboom(9)
_st_.blockend()
try:
 _st_.current_tex_line = 10
 _st_.plot(0, format='notprovided', _p_=plot(4*x^4+2*x^2-1,(x,-1,1)))
except:
 _st_.goboom(10)
_st_.endofdoc()
