## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file crap.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10)## This file (crap.sagetex.sage) was *autogenerated* from crap.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('crap', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_7 
_st_.blockbegin()
try:
 x=var(`x`)
except:
 _st_.goboom(_sage_const_9 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_10 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(_sage_const_4 *x**_sage_const_4 +_sage_const_2 *x**_sage_const_2 -_sage_const_1 ,(x,-_sage_const_1 ,_sage_const_1 )))
except:
 _st_.goboom(_sage_const_10 )
_st_.endofdoc()

